name: Deploy to Debian

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Create Test File in Home Directory
        run: |
          echo "Pipeline verified at $(date)" > ~/ci_cd_test.txt